Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "IaaS-Webserver"
        vb.memory = "2048"
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--groups", "/Vagrant-Labs"]
    end

    config.vm.network "private_netwrok", ip: "192.168.33.10"
    config.vm.hostname = "iaas-webserver"
    config.vm.provision "shell", path: "bootstrap.sh"
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end